# Generated by Django 3.2.5 on 2021-08-15 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_status',
            new_name='approved',
        ),
    ]
